#define DEBUG_FILE 0

#define DEBUG_MESH_START 0
#define DEBUG_PARAMETERS_ALL 0
#define DEBUG_INLET 0
#define DEBUG_SOLVE_BIDIAGONAL 0
#define DEBUG_STEP_IMPLICIT 0
#define DEBUG_STEP1 0
#define DEBUG_STEP2 0
#define DEBUG_SIMULATE 0

#define INLINE_LEVEL 0xffff
